import { CategoryOption, ProduceItem, SupplierStat, IncomingOrder } from './types';

export const categoryOptions: CategoryOption[] = [
  { id: 'all', label: 'All Grades', emoji: '🌿' },
  { id: 'husk_85', label: '85% Pure', emoji: '🌱', gradeName: 'Psyllium Husk 85% Pure' },
  { id: 'husk_95', label: '95% Pure', emoji: '🌿', gradeName: 'Psyllium Husk 95% Pure' },
  { id: 'husk_98', label: '98% Pure', emoji: '⭐', gradeName: 'Psyllium Husk 98% Pure' },
  { id: 'husk_99', label: '99% Pure', emoji: '💎', gradeName: 'Psyllium Husk 99% Pure' },
  { id: 'custom', label: 'Custom Grade', emoji: '✏️', gradeName: 'Type your required grade' },
];

export const sampleProduceList: ProduceItem[] = [
  {
    id: 'p1',
    name: 'Psyllium Husk 99% Pure (A-Grade Export)',
    grade: 'Psyllium Husk 99% Pure',
    category: 'husk_99',
    price: 340,
    unit: 'Kg',
    supplierName: 'Gujarat Botanical Co-op',
    moq: '250 Kg',
    rating: 4.9,
    isVerified: true,
    stockQty: 5000,
    imageEmoji: '💎',
  },
  {
    id: 'p2',
    name: 'Psyllium Husk 98% Pure (Super Fine)',
    grade: 'Psyllium Husk 98% Pure',
    category: 'husk_98',
    price: 290,
    unit: 'Kg',
    supplierName: 'Unjha Ispaghol Exporters',
    moq: '500 Kg',
    rating: 4.8,
    isVerified: true,
    stockQty: 10000,
    imageEmoji: '⭐',
  },
  {
    id: 'p3',
    name: 'Psyllium Husk 95% Pure (Standard Grade)',
    grade: 'Psyllium Husk 95% Pure',
    category: 'husk_95',
    price: 250,
    unit: 'Kg',
    supplierName: 'Sidhpur Psyllium Industry',
    moq: '1 Ton',
    rating: 4.7,
    isVerified: true,
    stockQty: 15000,
    imageEmoji: '🌿',
  },
  {
    id: 'p4',
    name: 'Psyllium Husk 85% Pure (Industrial Grade)',
    grade: 'Psyllium Husk 85% Pure',
    category: 'husk_85',
    price: 210,
    unit: 'Kg',
    supplierName: 'Rajasthan Spices & Herbs',
    moq: '2 Tons',
    rating: 4.6,
    isVerified: true,
    stockQty: 20000,
    imageEmoji: '🌱',
  },
  {
    id: 'p5',
    name: 'Psyllium Husk 99% Pure (Pharma Grade)',
    grade: 'Psyllium Husk 99% Pure',
    category: 'husk_99',
    price: 360,
    unit: 'Kg',
    supplierName: 'Apex Isabgol Processors',
    moq: '100 Kg',
    rating: 5.0,
    isVerified: true,
    stockQty: 3000,
    imageEmoji: '🧪',
  },
  {
    id: 'p6',
    name: 'Psyllium Husk 98% Pure (Commercial Bulk Pack)',
    grade: 'Psyllium Husk 98% Pure',
    category: 'husk_98',
    price: 275,
    unit: 'Kg',
    supplierName: 'National Ispagul Mills',
    moq: '5 Tons',
    rating: 4.8,
    isVerified: true,
    stockQty: 25000,
    imageEmoji: '📦',
  },
];

export const sampleSupplierStat: SupplierStat = {
  activeListings: 12,
  monthlyRevenue: 148500,
  pendingOrders: 5,
  totalDelivered: 48,
};

export const sampleIncomingOrders: IncomingOrder[] = [
  {
    id: 'ord-101',
    buyerName: 'Pharma Care Overseas',
    produceName: 'Psyllium Husk 99% Pure',
    quantity: '500 Kg',
    totalPrice: 170000,
    status: 'Pending',
    date: 'Today, 2:30 PM',
  },
  {
    id: 'ord-102',
    buyerName: 'HealthLife Food Industries',
    produceName: 'Psyllium Husk 98% Pure',
    quantity: '2 Tons',
    totalPrice: 580000,
    status: 'Accepted',
    date: 'Yesterday',
  },
  {
    id: 'ord-103',
    buyerName: 'Apex Bio Nutra',
    produceName: 'Psyllium Husk 95% Pure',
    quantity: '1 Ton',
    totalPrice: 250000,
    status: 'Shipped',
    date: 'Aug 07, 2026',
  },
];
