import { CategoryOption, ProduceItem, SupplierStat, IncomingOrder } from './types';

export const categoryOptions: CategoryOption[] = [
  { id: 'all', label: 'All Items', emoji: '🌾' },
  { id: 'grains', label: 'Grains & Pulses', emoji: '🌾' },
  { id: 'vegetables', label: 'Vegetables', emoji: '🥬' },
  { id: 'fruits', label: 'Organic Fruits', emoji: '🍎' },
  { id: 'inputs', label: 'Seeds & Fertilizer', emoji: '🧪' },
  { id: 'equipment', label: 'Tools & Tractors', emoji: '🚜' },
];

export const sampleProduceList: ProduceItem[] = [
  {
    id: 'p1',
    name: 'Sharbati Premium Wheat',
    category: 'grains',
    price: 2450,
    unit: 'Quintal',
    supplierName: 'Punjab Grain Co-op',
    location: 'Ludhiana, Punjab',
    moq: '10 Quintals',
    rating: 4.8,
    isOrganic: true,
    isVerified: true,
    stockQty: 250,
    imageEmoji: '🌾',
  },
  {
    id: 'p2',
    name: 'Royal Super Basmati Rice 1121',
    category: 'grains',
    price: 6200,
    unit: 'Quintal',
    supplierName: 'Karnal Rice Exporters',
    location: 'Karnal, Haryana',
    moq: '5 Quintals',
    rating: 4.9,
    isOrganic: false,
    isVerified: true,
    stockQty: 400,
    imageEmoji: '🍚',
  },
  {
    id: 'p3',
    name: 'Farm Fresh Hybrid Tomatoes',
    category: 'vegetables',
    price: 28,
    unit: 'Kg',
    supplierName: 'Nashik Vegetable Farms',
    location: 'Nashik, Maharashtra',
    moq: '100 Kg',
    rating: 4.6,
    isOrganic: true,
    isVerified: true,
    stockQty: 1200,
    imageEmoji: '🍅',
  },
  {
    id: 'p4',
    name: 'Organic Alphonso Mangoes',
    category: 'fruits',
    price: 850,
    unit: 'Dozen',
    supplierName: 'Ratnagiri Orchards',
    location: 'Ratnagiri, Maharashtra',
    moq: '5 Dozen',
    rating: 4.9,
    isOrganic: true,
    isVerified: true,
    stockQty: 150,
    imageEmoji: '🥭',
  },
  {
    id: 'p5',
    name: 'Bio-Organic NPK Fertilizer',
    category: 'inputs',
    price: 1350,
    unit: 'Bag (50kg)',
    supplierName: 'GreenCrop Agri Bio',
    location: 'Indore, MP',
    moq: '10 Bags',
    rating: 4.7,
    isOrganic: true,
    isVerified: true,
    stockQty: 500,
    imageEmoji: '🧪',
  },
  {
    id: 'p6',
    name: 'Mahindra 575 DI Tractor Hire',
    category: 'equipment',
    price: 1200,
    unit: 'Day',
    supplierName: 'Kisan Machinery Rental',
    location: 'Bathinda, Punjab',
    moq: '1 Day',
    rating: 4.8,
    isOrganic: false,
    isVerified: true,
    stockQty: 8,
    imageEmoji: '🚜',
  },
];

export const sampleSupplierStat: SupplierStat = {
  activeListings: 12,
  monthlyRevenue: 148500,
  pendingOrders: 5,
  totalDelivered: 48,
};

export const sampleIncomingOrders: IncomingOrder[] = [
  {
    id: 'ord-101',
    buyerName: 'Sharma Food Processing Ltd',
    produceName: 'Sharbati Premium Wheat',
    quantity: '20 Quintals',
    totalPrice: 49000,
    status: 'Pending',
    date: 'Today, 2:30 PM',
  },
  {
    id: 'ord-102',
    buyerName: 'Verma Wholesale Mandi',
    produceName: 'Farm Fresh Hybrid Tomatoes',
    quantity: '500 Kg',
    totalPrice: 14000,
    status: 'Accepted',
    date: 'Yesterday',
  },
  {
    id: 'ord-103',
    buyerName: 'Apex Organic Retail',
    produceName: 'Organic Alphonso Mangoes',
    quantity: '10 Dozen',
    totalPrice: 8500,
    status: 'Shipped',
    date: 'Aug 07, 2026',
  },
];
